### ISSUE TITLE
nbm-maven-plugin Pack200 is used or not?

### ISSUE THREAD

**Issue by jmborer** [apache/netbeans-mavenutils-nbm-maven-plugin#109]
When building NB applications with the nbm-maven-plugin and Maven, how do we know if Pack200 is used or not?

**Comment by mbien** [comment]
since pack200 doesn't exist anymore post JDK 14, you could try to build on JDK 17, if it works you know for sure that it is not used anywhere.

I hope it is everywhere off by default by now, the installer mojo #116 still had it enabled. If you still use the installer, consider the more modern replacement: 
https://github.com/apache/netbeans-nbpackage cc @neilcsmith-net
